In [1]:
import numpy as np  # import Numpy Libraray

* 1-D Array:

In [2]:
a=np.array([1,2,3])
print('Dimension of Array is:',a.ndim)
print('Array is:',a)


Dimension of Array is: 1
Array is: [1 2 3]


* Shape:
The shape of an array is the number of elements in each dimension.

In [3]:
print(a.shape)

(3,)


* finding the size of each item in the array  

In [4]:
print(a.itemsize)

4


* finding the data type of each array it

In [5]:
print(a.dtype)

int32


In [6]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 2-D array

In [7]:
a=np.array([[1,2,3]])
print('size of array is:',a.size)
print('Dimension of Array is:',a.ndim)

size of array is: 3
Dimension of Array is: 2


In [8]:
print(a.shape)  # Shape Tells That How many columns and rows available

(1, 3)


* 3-D Array:

In [9]:
a=np.array([[[1,2,3]]])
print('Dimension Of Array is:',a.ndim)
print(a)

Dimension Of Array is: 3
[[[1 2 3]]]


In [10]:
print(a.shape)

(1, 1, 3)


* Reshape Array:

In [11]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print('original array:',a)
a=a.reshape(2,3)
print('reshape array:',a)

original array: [[1 2]
 [3 4]
 [5 6]]
reshape array: [[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
b=a.reshape(4,1)
print(b)

[[1 2]
 [3 4]]
[[1]
 [2]
 [3]
 [4]]


* Slicing the Array:

In [13]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])

print(a[0,1])
print(a[2,-1])
print(a[2,0])

2
6
5


* Linspace

In [14]:
import numpy as np
a=np.linspace(5,15,8)
print(a)

[ 5.          6.42857143  7.85714286  9.28571429 10.71428571 12.14285714
 13.57142857 15.        ]


* Finding the maximum, minimum, and sum of the array elements:

In [15]:
import numpy as np
a=np.array([1,2,5,12,15,10,8,9])
print('Array elements of a:',a)
print('Maximum array:',a.max())
print('Minimum Array:',a.min())
print('sum of Array:',a.sum())

Array elements of a: [ 1  2  5 12 15 10  8  9]
Maximum array: 15
Minimum Array: 1
sum of Array: 62


* NumPy Array Axis:

In [16]:
a=np.array([[1,2,3],[4,5,6]])
print('The Array is:')
print(a)
print('The Maximum element of column:',a.max(axis=0))
print('The Minimum element of column:',a.min(axis=0))
print('The maximum element of row:',a.max(axis=1))
print('The minimum  element of row:',a.min(axis=1))

The Array is:
[[1 2 3]
 [4 5 6]]
The Maximum element of column: [4 5 6]
The Minimum element of column: [1 2 3]
The maximum element of row: [3 6]
The minimum  element of row: [1 4]


* Finding square root and standard deviation:

In [17]:
a=np.array([[1,8,9],[4,25,36]])
print('Array of a is:')
print(a)
print('Square root of a:')
print(np.sqrt(a))
print('Standard deviaion is:',)
print(np.std(a))

Array of a is:
[[ 1  8  9]
 [ 4 25 36]]
Square root of a:
[[1.         2.82842712 3.        ]
 [2.         5.         6.        ]]
Standard deviaion is:
12.482209562235187


* Arithmetic operations on the array:

In [18]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4],[5,7,9]])
print('Array is:')
print(a)
print('sum of addition',a+b)
print('division',a/b)
print('Multiplication',a*b)


Array is:
[[1 2 3]
 [4 5 6]]
sum of addition [[ 3  5  7]
 [ 9 12 15]]
division [[0.5        0.66666667 0.75      ]
 [0.8        0.71428571 0.66666667]]
Multiplication [[ 2  6 12]
 [20 35 54]]


* Array Concatenation:
* The numpy provides us with the vertical stacking and horizontal stacking which allows us to concatenate two multi-dimensional
* arrays vertically or horizontally.

In [19]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print('verticall of a is:')
print(np.vstack(a))
print('horizontal of a is:')
print(np.hstack(a))
print('vertically of a&b is:')
print(np.vstack((a,b)))
print('horizontally of a&b is:')
print(np.hstack((a,b)))


verticall of a is:
[[1 2 3]
 [4 5 6]]
horizontal of a is:
[1 2 3 4 5 6]
vertically of a&b is:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
horizontally of a&b is:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [20]:
a=np.array([[1,2,3],[5,6,7]])
print(np.vstack(a))
print(np.hstack(a))

[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7]


* Numpy empty:

In [21]:
import numpy as np
a=np.empty((3,2),dtype=int)
print(a)

[[1 2]
 [3 5]
 [6 7]]


* NumPy Zeros Function:

In [22]:
a=np.zeros((3,2),dtype=int)
print(a)

[[0 0]
 [0 0]
 [0 0]]


* NumPy ones Function:

In [23]:
a=np.ones((3,2),dtype=int)
print(a)

[[1 1]
 [1 1]
 [1 1]]


* numpy.asarray:
* creating numpy array using the list:

In [24]:
import numpy as np
l=[1,2,3,4,5,6,7]
print(l)
print('Before Using Numpy is:',type(l))
a=np.array(l)
print('After Using Numpy is',type(a))
print(a)

[1, 2, 3, 4, 5, 6, 7]
Before Using Numpy is: <class 'list'>
After Using Numpy is <class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


* creating a numpy array using Tuple

In [25]:
t=(1,2,3,4,5,6,7)
print('Before Using Numpy is:',type(t))
print(t)
a=np.array(t)
print('After Using Numpy is:',type(a))
print(a)

Before Using Numpy is: <class 'tuple'>
(1, 2, 3, 4, 5, 6, 7)
After Using Numpy is: <class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


* eye function:-diagonal  Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [26]:
a=np.eye(3)  
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [28]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* create array using diag function:

In [29]:
a=np.diag((1,2,3,4))
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [30]:
np.diag(a)  # Extract diagonal

array([1, 2, 3, 4])

* create array using random

* Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1]).

In [31]:
a=np.random.rand(4)
print('Random array is:',a)

Random array is: [0.96464292 0.01034844 0.90893919 0.62755206]


In [32]:
a=np.random.rand()
print(type(a))
print(a)

<class 'float'>
0.514600745657358


In [33]:
# Basic data types:

a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(a.dtype)

int32


In [35]:
a=np.arange(10,dtype='float')
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [36]:
a=np.arange(10,dtype=int)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [37]:
a=np.array([True,False,True,False])
print(a)
print(type(a))

[ True False  True False]
<class 'numpy.ndarray'>


In [38]:
a=np.diag((1,2,3))
print(a)
print(type(a))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
<class 'numpy.ndarray'>


In [39]:
print(a[2,2])

3


In [40]:
a=np.arange(10)
print(a[5:])

[5 6 7 8 9]


In [41]:
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [42]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [43]:
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [44]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
b=a[::2]

In [46]:
b

array([0, 2, 4, 6, 8])

In [47]:
np.shares_memory(a,b)

True

In [48]:
a=np.random.randint(0,20,15)
a

array([ 9,  1,  2,  2,  4,  9,  9, 18, 11, 10,  4, 12, 19, 16, 18])

In [49]:
mask=(a%2==0)

In [50]:
extract_from_a=a[mask]
extract_from_a

array([ 2,  2,  4, 18, 10,  4, 12, 16, 18])

In [51]:
a[mask]=-1
a

array([ 9,  1, -1, -1, -1,  9,  9, -1, 11, -1, -1, -1, 19, -1, -1])

In [52]:
# NumPy Broadcasting:

import numpy as np
a=np.array([1,2,3,4,5,6,7])
b=np.array([2,4,6,8,10,12,14])
c=a*b
print(c)

[ 2  8 18 32 50 72 98]


In [53]:
# NumPy Array Iteration:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('array')
print(a)
print('over iterate the array')
for i in np.nditer(a):
    print(i,end=',')

array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
over iterate the array
1,2,3,4,5,6,7,8,9,10,11,12,

In [54]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('array')
print(a)
print('over transpose')
at=a.T
print(at)

array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
over transpose
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [55]:
# NumPy String Functions:
import numpy as np
print('cancatination of str function')
print(np.char.add(['welcome','hi'],['khan','read python']))

cancatination of str function
['welcomekhan' 'hiread python']


In [56]:
# multiply:

print(np.char.multiply('khan',3))

khankhankhan


* Array Math:

In [57]:
import numpy as np

In [58]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,6],[7,8,9]])
print(a+b)
print('-----------')
print(np.add(a,b))

[[ 5  7  9]
 [11 13 15]]
-----------
[[ 5  7  9]
 [11 13 15]]


In [59]:
print(a-b)
print('_____________')
print(np.subtract(a,b))

[[-3 -3 -3]
 [-3 -3 -3]]
_____________
[[-3 -3 -3]
 [-3 -3 -3]]


In [60]:
print(a*b)
print(np.multiply(a,b))

[[ 4 10 18]
 [28 40 54]]
[[ 4 10 18]
 [28 40 54]]


In [61]:
print(a/b)
print(np.divide(a,b))

[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]


In [62]:
print(a*a)
print(np.square(a))

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [63]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])


In [64]:
x

array([[1, 2],
       [3, 4]])

In [65]:
y

array([[5, 6],
       [7, 8]])

In [66]:

print(v.dot(w))
print(np.dot(v, w))
print(x.dot(y))

219
219
[[19 22]
 [43 50]]
